### ISSUE TITLE
NIM anywhere control panel view and config file terms don't align

### ISSUE THREAD

**Issue by freemansoft** [NVIDIA/nim-anywhere#16]
This is probably me being a newbie but I don't understand what I'm looking at on this screen.  

## What are the names in the diagram correlated to in `config.yaml`? 

![image](https://github.com/user-attachments/assets/0983cad5-37de-4446-8d4d-6803139d816c)

The diagram shows
* Retrieval NIM
* Reranker NIM
* LLM NIM

`config.yaml` contains
* chat_model
* embedding model
* reranking model

Also...

## Chain Server Configuration

The bottom half of the image shows the `Chain Server Configuration` but I don't see anything called "chain server" in the diagram above. I'm assuming that it is one of the NIMs? `chain.py` mentions a bunch of components so I'm not sure why the bottom diagram only includes the chat_model.

**Comment by rmkraus** [comment]
Very interesting feedback. Thank you! Its good to be able to see the UI through someone else's eyes!

To answer your questions: 
- the architecture diagram is the internal architecture of the chain server
- retrieval nim <--> embedding_model
- reranker nim <--> reranking model
- llm nim <--> chat_model

---

To make this more clear, I think we could make the following changes:

- [ ] Rename the Retrieval Configuration accordion to Chain Server Architecture
- [ ] In the diagram, rename Retrieval NIM to "Embedding", no NIM in name
- [ ] in the diagram, rename Reranker NIM to "Reranker", no NIM in name
- [ ] in the diagram, rename LLM NIM to "LLM", no nim in name
- [ ] in the configuration file, rename "chat_model" to "llm_model"

That would mean the diagram would show:
- Embedding
- Reranker
- LLM

The config would have:
- embedding_model
- reranker_model
- llm_model

And the top diagram would be labeled as the chain server architecture.

---

what do you think about those proposed changes?

**Comment by freemansoft** [comment]
The "milvus" entry in config.sys is which database in the diagram?
* Enterprise data
* Chat History
* Something else
