### ISSUE TITLE
Changes for demo creation - reranking and embedding checklist 

### ISSUE THREAD

**Issue by arharpster99** [NVIDIA/nim-anywhere#38]
When you first load up the chain server and frontend UI, the reranking and embedding models are checkmarked like they are in use, if we want to show this as a demo, this hurts our ability to do so, these should be off by default, and we should have users try the chatbot with reranking and embedding off first, then have them turn it on within workbench or the chat frontend UI, and have them ask the same question again to show how it enhances the results.

**Comment by AmeliaYe** [comment]
Should make change on the NIM Anywhere flowchart UI instead of the LangServe Playground

**Comment by AmeliaYe** [comment]
Fixed. https://github.com/NVIDIA/nim-anywhere/pull/41
