### ISSUE TITLE
Layout of spec.yaml changed in PR 31 and workstation rewrites that file out back in the old format.

### ISSUE THREAD

**Issue by freemansoft** [NVIDIA/nim-anywhere#42]
Looks like this PR moved the top section of spec.yaml to the bottom.

https://github.com/NVIDIA/nim-anywhere/pull/31/files

AI Workstation loads that file and then writes it out to disk putting the order back to the way it was prior to PR 31.  This causes the filesystem to be dirty. 

I had to actually delete my clone and recreated it to be able to run the project.

**Comment by AmeliaYe** [comment]
Hi Joe, to make sure this doesn't happen again, here are some suggestions: 

1. Update workbench to the latest version 
2. Use `git update-index --assume-unchanged [<file> ...]` to ignore any changes workbench makes to yaml file. We'll report this to the workbench team.
