### ISSUE TITLE
mistakenly set podman rather than docker as my container runtime

### ISSUE THREAD

**Issue by mrpointzby** [NVIDIA/nim-anywhere#46]
When I followed the instruction to do a Windows install of NVIDIA AI Workbench, I mistakenly selected podman rather than docker as my container runtime.
Then when I followed in the later guidance to toggle on Milvus Vector DB and redis, I failed.
So I suspected the reason for the latter failure is because I set wrong before.
Can you tell me how to change  back to docker of the settings? I didn't see anything in NVIDIA AI Workbench setting to change it right.

[workbench.log](https://github.com/user-attachments/files/16907202/workbench.log)

**Comment by jtcasablanca** [comment]
Hi. sorry for taking so long to respond.

You can swap out the container runtime choice by following the [instructions here](https://docs.nvidia.com/ai-workbench/user-guide/latest/reference/runtimes.html#change-your-container-runtime).

Basically you just need to change `docker` to `podman` in a configuration file and then fully quit and restart the application.

It will guide you through the steps after that.

You can go back and forth between the runtimes this way, *but* you may need to rebuild some containers.
