### ISSUE TITLE
The latest version of Workbench increases the version of spec.yaml to specMinorVersion:2

### ISSUE THREAD

**Issue by freemansoft** [NVIDIA/nim-anywhere#54]
The latest version of Workbench updates the `specMinorVersion` and changes the timeouts.  This repo should be updated to contain the latest Workbench values.

**Replication**
1. Open the project in the latest Workbench. 
2. spec.yaml will be updated

**Comment by rmkraus** [comment]
Thanks for reporting!

Looks like @AmeliaYe got this one in another PR.
