### ISSUE TITLE
AI Workstation doesn't shutdown redis or milvusdb containers when you stop the environment

### ISSUE THREAD

**Issue by freemansoft** [NVIDIA/nim-anywhere#6]
## Expected behavior

All nim-anywhere containers exit when the `project-nim-anywhere` container exits or when `AI Workstation` executes a `stop environment`

## Actual behavior
`redis` and `milvusdb/milvus` both continue to run after `stop environment` was executed _and_ `AI Workstation` was exited

## Test Sequence
1. Initial State
![image](https://github.com/user-attachments/assets/6148dc0f-6584-47f6-b47e-7dda294d349b)
![image](https://github.com/user-attachments/assets/47699d69-9594-4143-bdb4-ab8eac4a3109)
2. State after exiting AI Workstation

![image](https://github.com/user-attachments/assets/8a98aca5-3fc5-4196-9a4c-65c556313200)

**Comment by rmkraus** [comment]
That is correct. AI workbench does not currently handle shutting down these applications. We have a feature request in to the workbench team and future features should help alleviate this problem.
