### ISSUE TITLE
llm-nim-0.sh and llm-nim-1.sh should source model and gpus from variables.env

### ISSUE THREAD

**Issue by freemansoft** [NVIDIA/nim-anywhere#7]
Variables.sh defines the model and the GPUs to use but those values are ignored by the llm-nim-x.sh scripts.

**Comment by rmkraus** [comment]
Sacre bleu! You are correct! I'll get this fixed up.

**Comment by rmkraus** [comment]
This should now be fixed if you pull the latest code changes.
